server:
  #  port: 9594
#  port: 9590
  port: 9998

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/bae?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
springdoc:
  api-docs:
    path: /bae/api-docs
  swagger-ui:
    path: /bae/swagger-ui.html
app:
  jwtSecret: JWTMyBae
  jwtExpirationInMs: 315360000004
  firebase-configuration-file: diseno-b9d2b-firebase-adminsdk-1qqor-83ec47945d.json
  firebase-teacher-file: devonekidteacher-firebase-adminsdk-7gnma-856d17ca45.json
  firebase-plus-file: devonekidplus-firebase-adminsdk-clboc-52f9ec60a4.json
  firebase-database-file: fir-a08d2-firebase-adminsdk-heo0q-b97aa4cc27.json

